{{- if .Values.hosts -}}
{{- $fullName := include "certificate.fullname" . -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
{{ include "certificate.labels" . | indent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ .Release.Name }}-secret
  dnsNames:
  {{- range .Values.hosts }}
    - {{ . }}
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: azure/application-gateway
      domains:
      {{- range .Values.hosts }}
        - {{ . }}
      {{- end }}
  issuerRef:
    name: {{ .Values.clusterIssuer  }}
    kind: ClusterIssuer
{{- end }}
