include:
  - /charts/certificate/.gitlab-ci.yml
  - /charts/nodejs/.gitlab-ci.yml
  - /plugins/just/.gitlab-ci.yml
#

stages:
  - "Code Quality"
  - "Release"

Lint:
  stage: "Code Quality"
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:0.11.1
  script:
    - helm lint charts/*

#

Release:
  stage: "Release"
  image: node:10
  only:
    refs:
      - branches
  when: manual
  variables:
    GIT_AUTHOR_EMAIL: 45039513+SocialGroovyBot@users.noreply.github.com
    GIT_AUTHOR_NAME: Social Groovy Bot
    GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
    GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
    RELEASE_URL: https://github.com/${CI_PROJECT_PATH}/releases/download
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_PROJECT_DIR/.yarn
  before_script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
  script:
    # Installing Helm
    - curl -L https://git.io/get_helm.sh | bash
    - helm init --client-only
    # Installing semantic-release
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn global add semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git
    #
    - semantic-release

#
