stages:
  - "Code Quality"
  - "Release"

Lint:
  stage: "Code Quality"
  image: ${CI_REGISTRY}/socialgouv/docker/helm:0.3.0
  script:
    - helm lint webapp

#

Release:
  stage: "Release"
  image: node:10
  only:
    - master
  when: manual
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_PROJECT_DIR/.yarn
  before_script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git config user.name "Social Groovy Bot"
    - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn global add semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git
    - semantic-release

#
