plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/exec"
    - prepareCmd: >-
        mkdir -p dist &&
        "sed -i -e 's/version: .*/version: ${nextRelease.version}/g' */Chart.yaml"
      prepareCmd:
      publishCmd: helm package webapp --destination dist/
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
  - - "@semantic-release/github"
    - assets:
        - label: Social Gouv Helm Charts
          path:
            - dist/**
