plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/exec"
    - prepareCmd: "
        sed -i -e 's/version: .*/version: ${nextRelease.version}/g' charts/*/Chart.yaml &&
        mkdir -p dist &&
        helm package charts/* --destination dist/ &&
        helm repo index ./dist
          --merge index.yaml
          --url $RELEASE_URL/${nextRelease.gitTag} &&
        cp ./dist/index.yaml ./index.yaml
        "
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - index.yaml
        - charts/*/Chart.yaml
      message: "
        chore(release): version ${nextRelease.version}
        \n
        \n
        ${nextRelease.notes}
      "
  - - "@semantic-release/github"
    - assets:
        - path:
            - dist/**
