#

Test socialgouv/app:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:0.29.0
  script:
    # Use default socialgouv values
    - envsubst < ./charts/app/values.socialgouv.yaml > /tmp/values.socialgouv.yaml
    #
    - envsubst < ./charts/app/values.test.yaml > /tmp/values.yaml
    - cat /tmp/values.yaml
    #
    - kubectl config set-context --current --namespace=default
    - helm delete --purge helm-chart-app-${CI_JOB_ID} || true
    - helm upgrade
        helm-chart-app-${CI_JOB_ID}
        ./charts/app
        --debug
        --install
        --values /tmp/values.socialgouv.yaml
        --values /tmp/values.yaml
        --wait
    - helm test helm-chart-app-${CI_JOB_ID} --cleanup --debug
  after_script:
    - helm delete --purge helm-chart-app-${CI_JOB_ID} || true
