#

Test socialgouv/app:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:1.0.0
  script:
    # Use default socialgouv values
    # The `values.socialgouv.yaml` requires a PORT to be defined !
    - export PORT=80
    - envsubst < ./charts/app/values.socialgouv.yaml > /tmp/values.socialgouv.yaml
    - cat /tmp/values.socialgouv.yaml
    #
    - envsubst < ./charts/app/values.test.yaml > /tmp/values.yaml
    - cat /tmp/values.yaml
    #
    - kubectl config set-context --current --namespace=helm-charts-app
    - helm init --client-only
    - helm delete --purge chart-app-${CI_JOB_ID} || true
    - helm upgrade
      chart-app-${CI_JOB_ID}
      ./charts/app
      --debug
      --install
      --values /tmp/values.socialgouv.yaml
      --values /tmp/values.yaml
      --wait
    - helm test chart-app-${CI_JOB_ID} --cleanup --debug
  after_script:
    - helm delete --purge chart-app-${CI_JOB_ID} || true
