---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "managed-pg.fullname" . }}-migrate
  labels:
    app: migrate
{{ include "managed-pg.labels" . | indent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
{{ include "managed-pg.labels" . | indent 8 }}
    spec:
      containers:
        - name:  "{{ include "managed-pg.fullname" . }}-migrate"
          image: "{{ .Values.migrate.image }}"
          imagePullPolicy: IfNotPresent
          command:
            - {{ .Values.migrate.command }}
          envFrom:
          - secretRef:
              name: azure-pg-user
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
      restartPolicy: {{ .Values.restartPolicy }}
