---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}{{ .Values.hashBranch }}
  labels:
    app: {{ .Release.Name }}{{ .Values.hashBranch }}
    branch: {{ .Release.Name }}{{ .Values.hashBranch }}
    chart: {{ template "webapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ .Release.Name }}{{ .Values.hashBranch }}
    release: {{ .Release.Name }}
