#

Test socialgouv/hpa:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:0.25.0
  script:
    - kubectl config set-context --current --namespace=default
    - helm delete --purge helm-chart-hpa-${CI_JOB_ID} || true
    - helm upgrade
        helm-chart-hpa-${CI_JOB_ID}
        ./charts/hpa
        --debug
        --install
        --values ./charts/hpa/values.test.yaml
        --wait
    - helm test helm-chart-hpa-${CI_JOB_ID} --cleanup --debug
  after_script:
    - helm delete --purge helm-chart-hpa-${CI_JOB_ID} || true
