# Default values for nodejs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: node
  tag: lts-alpine
  pullPolicy: IfNotPresent

deployment:

  annotations: {}

  replicaCount: 1
  imagePullSecrets: []

  port: 80

  livenessProbe:
    initialDelaySeconds: 5
    path: /
    periodSeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    path: /
    periodSeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
  resources:
    limits:
      cpu: 50m
      memory: 32Mi
    requests:
      cpu: 5m
      memory: 16Mi

  env:
    - name: PORT
      value: "80"
    - name: NODE_ENV
      value: "production"

  nodeSelector: {}

  tolerations: []

  affinity: {}

  initContainers: []

ingress:
  enabled: false
  annotations: {}
    # appgw.ingress.kubernetes.io/ssl-redirect: "true"
    # certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    # kubernetes.io/ingress.class: "azure/application-gateway"
    # kubernetes.io/tls-acme: "true"
  hosts: []
    # - host: test.nodejs.dev.fabrique.social.gouv.fr
    #   paths:
    #     - /
  tls: []
    # - hosts:
    #     - test.nodejs.dev.fabrique.social.gouv.fr
    #   secretName: emjpm-certificate-2b0c345-secret

fullnameOverride: ""
nameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: http
