# Test values for certificate.

image:
  repository: djfarrelly/maildev
  tag: 1.1.0

labels:
  app.kubernetes.io/part-of: helm-charts
  owner: default # where the project is in the cluster
  team: helm-charts # the github "team" or repo name

deployment:

  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}

  env:
    - name: PORT
      value: "80"
    - name: NODE_ENV
      value: "test"

  livenessProbe:
    initialDelaySeconds: 5
    path: /
    port: 80
    periodSeconds: 3
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 5
    path: /
    port: 80
    periodSeconds: 3
    failureThreshold: 3
    timeoutSeconds: 5

  initContainers:
    - name: test-init-containers
      image: alpine:3.10
      command:
        - sh
        - -c
        - |
          echo Ready;

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: "azure/application-gateway"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: test.nodejs.chart.dev.fabrique.social.gouv.fr
      paths:
        - path: /
          servicePort: 4000
  tls:
    - hosts:
        - test.nodejs.chart.dev.fabrique.social.gouv.fr
      secretName: helm-chart-certificate-nodejs
