# Test values for certificate.

image:
  repository: djfarrelly/maildev
  tag: 1.1.0

deployment:
  env:
    - name: PORT
      value: "80"
    - name: NODE_ENV
      value: "test"

  initContainers:
    - name: test-initContainers
      image: alpine:3.10
      command:
        - sh
        - -c
        - |
          echo Ready;

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: "azure/application-gateway"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: test.nodejs.chart.dev.fabrique.social.gouv.fr
      paths:
        - /
  tls:
    - hosts:
        - test.nodejs.chart.dev.fabrique.social.gouv.fr
      secretName: helm-chart-certificate-nodejs
