{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
{{- if .Values.autoscaling.targetCPUAverageUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.autoscaling.targetCPUAverageUtilizationPercentage }}
          type: Utilization
{{- end }}
{{- if .Values.autoscaling.targetMemoryAverageUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ .Values.autoscaling.targetMemoryAverageUtilizationPercentage }}
          type: Utilization
{{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
{{- end }}
