#

Test socialgouv/certificate:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  only:
    changes:
      - charts/certificate/**/*
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:0.10.0
  script:
    - kubectl config set-context --current --namespace=default
    - helm delete --purge helm-chart-certificate-${CI_JOB_ID} || true
    - helm upgrade
        helm-chart-certificate-${CI_JOB_ID}
        ./charts/certificate
        --debug
        --install
        --values ./charts/certificate/values.test.yaml
        --wait
    - helm test helm-chart-certificate-${CI_JOB_ID} --cleanup --debug
  after_script:
    - helm delete --purge helm-chart-certificate-${CI_JOB_ID} || true
