#

Test socialgouv/managed-pg:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:1.0.0
  variables:
    JUST_CHARTS_DIRECTORY: charts
  script:
    - kubectl config set-context --current --namespace=helm-charts-managed-pg
    #
    - helm init --client-only
    #
    # hack just: increase timeout and remove available test, just completed
    - cat ./plugins/just/just.sh | sed s/--timeout=5s/--timeout=30s/ > ./plugins/just/just.sh2
    - mv ./plugins/just/just.sh2 ./plugins/just/just.sh
    - chmod +x ./plugins/just/just.sh
    #
    - helm plugin install ./plugins/just
    #
    #
    - bats -t ./charts/managed-pg/test

    #
    - export RELEASE_NAME=${RELEASE_NAME:="create-db-user-test-${CI_COMMIT_SHORT_SHA}"}
    - helm just test "${RELEASE_NAME}"

    #
    - bats ./charts/managed-pg/test/30-drop-db-user.bats -t
    # todo: test DB destroyed

  after_script:
    - kubectl config set-context --current --namespace=helm-charts-managed-pg
    - helm just delete "helm-chart-managed-pg-test-${CI_JOB_ID}" || true
