#

Test socialgouv/managed-pg:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:1.15.0
  variables:
    JUST_CHARTS_DIRECTORY: charts
  script:
    - kubectl config set-context --current --namespace=helm-charts-managed-pg
    # Copy `azure-pg-admin-user` secret to `helm-charts-managed-pg`
    - kubectl get secrets -n helm-charts-secret azure-pg-admin-user -o yaml |
        sed 's/namespace.*helm-charts-secret//' |
        kubectl apply --force -f -

    #
    - helm init --client-only
    #
    # hack just: increase timeout and remove available test, just completed
    - cat ./plugins/just/just.sh | sed s/--timeout=5s/--timeout=30s/ > ./plugins/just/just.sh2
    - mv ./plugins/just/just.sh2 ./plugins/just/just.sh
    - chmod +x ./plugins/just/just.sh
    #
    - helm plugin install ./plugins/just
    #
    # NOTE(douglasduteil): try to drop before tests
    # Ensure that the database doesn't exist
    - bats ./charts/managed-pg/test/30-drop-db-user.bats -t || true
    #
    - bats ./charts/managed-pg/test/10-create-db-user.bats -t
    - bats ./charts/managed-pg/test/20-migrate.bats -t
    - bats ./charts/managed-pg/test/25-seed.bats -t

    #
    - export RELEASE_NAME=${RELEASE_NAME:="create-db-user-test-${CI_COMMIT_SHORT_SHA}"}
    - helm just test "${RELEASE_NAME}"

    #
    - bats ./charts/managed-pg/test/30-drop-db-user.bats -t
    # todo: test DB destroyed

  after_script:
    - kubectl config set-context --current --namespace=helm-charts-managed-pg
    - helm just delete "helm-chart-managed-pg-test-${CI_JOB_ID}" || true
