#

Test socialgouv/managed-pg:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:0.25.0
  variables:
    JUST_CHARTS_DIRECTORY: charts
  script:
    - kubectl config set-context --current --namespace=helm-charts-test
    #
    - helm init --client-only
    - helm plugin install ./plugins/just
    #
    - BRANCH_NAME_HASHED=$( printf "${CI_COMMIT_REF_SLUG}" | sha1sum | cut -c1-7 )
    - helm just render "helm-chart-managed-pg-test-${CI_JOB_ID}" managed-pg
      --set db.name="db_${BRANCH_NAME_HASHED}"
      --set db.password="pass_${BRANCH_NAME_HASHED}"
      --set db.user="user_${BRANCH_NAME_HASHED}"
    #
    # Clean up case
    - helm just apply "helm-chart-managed-pg-test-${CI_JOB_ID}" -l app=drop-db-user
    # Wait for the drop to fail fast if the db doesn't exist
    # If it's not failing withing the first 20s, wait for it to succeed as the db exists
    - kubectl wait --for=condition=failed "job/helm-chart-managed-pg-test-${CI_JOB_ID}-drop-db-user" --timeout=20s ||
      kubectl wait --for=condition=complete "job/helm-chart-managed-pg-test-${CI_JOB_ID}-drop-db-user" --timeout=1m
    - helm just delete "helm-chart-managed-pg-test-${CI_JOB_ID}" -l app=drop-db-user
    - kubectl wait --for=delete "job/helm-chart-managed-pg-test-${CI_JOB_ID}-drop-db-user" --timeout=30s || true
    #
    #
    #
    - helm just apply "helm-chart-managed-pg-test-${CI_JOB_ID}" -l app=create-db-user
    - kubectl wait --for=condition=complete "job/helm-chart-managed-pg-test-${CI_JOB_ID}-create-db-user" --timeout=2m
    - helm just test "helm-chart-managed-pg-test-${CI_JOB_ID}"
      --set db.name="db_${BRANCH_NAME_HASHED}"
    #
    - helm just apply "helm-chart-managed-pg-test-${CI_JOB_ID}" -l app=drop-db-user
    - kubectl wait --for=condition=complete "job/helm-chart-managed-pg-test-${CI_JOB_ID}-drop-db-user" --timeout=2m

  after_script:
    - kubectl config set-context --current --namespace=helm-charts-test
    - helm just delete "helm-chart-managed-pg-test-${CI_JOB_ID}" || true
