#

Test socialgouv/managed-pg:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:8327bfab7b1ed373bd95056c31aa3fdbe2c8fa0c
  variables:
    JUST_CHARTS_DIRECTORY: charts
  script:
    - kubectl config set-context --current --namespace=helm-charts-managed-pg
    #
    - helm init --client-only
    #
    # hack just: increase timeout and remove available test, just completed
    - cat ./plugins/just/just.sh | sed s/--timeout=5s/--timeout=30s/ > ./plugins/just/just.sh2
    - mv ./plugins/just/just.sh2 ./plugins/just/just.sh
    - chmod +x ./plugins/just/just.sh
    #
    - helm plugin install ./plugins/just
    #
    #
    #
    - bats -t ./charts/managed-pg/test

  after_script:
    - kubectl config set-context --current --namespace=helm-charts-managed-pg
    - helm just delete "helm-chart-managed-pg-test-${CI_JOB_ID}" || true
