#

Test socialgouv/managed-pg:
  stage: "Code Quality"
  environment:
    name: fabrique-dev
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:1.0.0
  variables:
    JUST_CHARTS_DIRECTORY: charts
  script:
    - kubectl config set-context --current --namespace=helm-charts-managed-pg
    #
    - helm init --client-only
    - helm plugin install ./plugins/just
    #
    # NOTE(douglasduteil): try to drop before tests
    # Ensure that the database doesn't exist
    - bats ./charts/managed-pg/test/drop-db-user.bats -t || true
    #
    - bats ./charts/managed-pg/test/create-db-user.bats -t
    - bats ./charts/managed-pg/test/drop-db-user.bats -t

  after_script:
    - kubectl config set-context --current --namespace=helm-charts-managed-pg
    - helm just delete "helm-chart-managed-pg-test-${CI_JOB_ID}" || true
