apiVersion: v1
name: managed-pg
version: 6.2.0
appVersion: 1.0
home: https://github.com/SocialGouv/helm-charts/tree/master/charts/managed-pg
description: Social Gouv Managed Postgres Helm chart for Kubernetes
icon: https://azurecomcdn.azureedge.net/cvt-7f20918d0143618d134d358f250496fac09c05555c7f626c7cb3ea673a2ddcaf/less/images/section/postgresql.jpg
keywords:
  - Managed
  - Postgres
  - managed-pg
sources:
  - https://github.com/SocialGouv/helm-charts/tree/master/charts/managed-pg
maintainers:
  - name: Incubateur des Ministères Sociaux
    email: dsi-incubateur@sg.social.gouv.fr
