# Default values for managed-pg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

jobs:
  image:
    repository: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/azure-db
    tag: "0.28.0"
    pullPolicy: IfNotPresent

  env:
    - name: PGSSLMODE
      value: "require"
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          name: azure-pg-admin-user
          key: PG_HOST
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: azure-pg-admin-user
          key: ADMIN_PG_USER
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: azure-pg-admin-user
          key: ADMIN_PG_PASSWORD

  restartPolicy: Never

createDb:
  name: "new_db"
  password: "new_pass"
  user: "new_user"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 0m
    memory: 0Mi
  limits:
    cpu: 1000m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
