# Default values for managed-pg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Azure DB image
## Most jobs need our `azure-db` image to work
image:
  repository: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/azure-db
  tag: "0.28.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

## The postgres database job subject
db:
  ## The database name to create or drop
  name: "new_db"
  ## The new user name to create or drop
  user: "new_user"
  ## The new user password
  password: "new_pass"

## jobs default env
env:
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: azure-pg-admin-user
        key: PGSSLMODE
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: azure-pg-admin-user
        key: PGHOST
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: azure-pg-admin-user
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: azure-pg-admin-user
        key: PGPASSWORD

## jobs restart policy
restartPolicy: Never

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    cpu: 0m
    memory: 0Mi
  limits:
    cpu: 1000m
    memory: 512Mi
