{{- if .Values.ingress.enabled -}}
{{- $fullName := .Release.Name -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $hashBranch := .Values.hashBranch -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}{{ $hashBranch }}
  labels:
    app: {{ $fullName }}{{ $hashBranch }}
    branch: {{ $fullName }}{{ $hashBranch }}
    chart: {{ template "webapp.chart" . }}
    release: {{ $fullName }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}{{ $hashBranch }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
